# Generated by Django 2.0.5 on 2018-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('Name', models.CharField(max_length=200)),
                ('Room_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
